### PR TITLE
Front End Fixes

### PR DESCRIPTION
**Pull request by veroniquehagen**
i did a few front end fixes. please have a look and see if everything is okay. 

The form for Add New event is faulty. we need to fix that tomorrow during our call. 

I would like to do it myself so i can learn but just need some guidance to ensure its done correctly.

### CODE REVIEW

**Comment by max13h** [comment]
Hello @veroniquehagen 

There is some issues in your PR

- event doesn't have a location
- events/new is not up to date and :time must be :date
- kids/show must be init with the focus layout and not put this "back" code directly in the page

**Comment by max13h** [comment]
Actually in my pr I fix new task and event to fit validations

**Comment by veroniquehagen** [comment]
@max13h i have made the above changes but I haven’t pushed them because there is no migration for location and time. So the form keeps coming up with an error. 

If possible can you not change anything or do anything towards this until we meet tonight because I want to learn where the mistakes are and how I can fix them.

**Comment by max13h** [comment]
Because your time is set as "date" in db and there is no location in db

**Comment by veroniquehagen** [comment]
@max13h i didn’t do the DB but thank you I’ll have a look after work and make sure everything is working and push through the changes I made for the form. 

Then there hopefully shouldn’t be an issue with the merge. 

Thank you for the help

**Pull request closed without merging**
